---
title: "BST430 - Introduction to Statistical Computing"
description: "University of Rochester, Fall 2023"
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

```

# Administrivia

MW 9:10-10:50, SRB 1406
<br>
**Instructor**: Matt McCall
<br>
**TA**: Alex Guo
<br>
**TA Office Hours**: Friday 9-10am in SRB 4.103
<br>
**Website**: https://bst-urmc.github.io/bst430-fall2023-site/
<br>
[**Syllabus**](static/bst430syllabus.pdf)
<br>
**Resources**:
    1. [install GIT](https://happygitwithr.com/install-git.html)
    2. [install *base* R](https://cran.r-project.org/)
    3. [install RStudio](https://www.rstudio.com/products/rstudio/download/#download)

# Content

0. [Introduction](lecture/l00-intro.html)
1. [Meet the toolkit](lecture/l01-meet-toolkit.html)
    * Invites to GitHub class room are on [blackboard](https://learn.rochester.edu)
    * Req readings: r4ds 3.1-3.5, 4. 
    * Optional readings: https://happygitwithr.com/
    * Lab 0 [instructions](hw_lab_instruction/lab00-demonstration/lab00-hello-class.html) and repo (accept GH classroom invite in Blackboard).

2. [ggplot(i)](lecture/l02-ggplot2-i.html)
    * [styleguide](lecture/l06-style.html)
    * Lab 1 [instructions](hw_lab_instruction/lab01-hello-r/lab01-hello-r.html) and repo (accept GH classroom [invite](https://classroom.github.com/a/9t7d6m5g). Due 5pm, Sept 11.
<!--     * Lab 1 [solutions](hw_lab_instruction/lab01-hello-r/lab01-hello-r.html) --> 
3.  [dplyr(i)](lecture/l03-transform-dplyr-i.html)
     * Continue working on Lab 1 

4.  [Data types in R](lecture/l04-data-types.html).
     * HW 1 assigned.  [instructions](hw_lab_instruction/hw-01-airbnb/hw-01-airbnb.html) and repo (accept GH classroom [invite](https://classroom.github.com/a/wfotYeNa)).
     
     <!-- * HW 1 [solutions](hw_lab_instruction/hw-01-airbnb/hw-01.html) -->

5.  [Reshaping and combining data frames](lecture/l05a-reshape-merge.html).
    *  [Lab 2](hw_lab_instruction/lab02-merge-conflict/lab02-merge-conflict.html). You will need to accept the [invitation](https://classroom.github.com/a/R_14OWgR).
    
<!--      * Lab 2 [solutions](hw_lab_instruction/lab02-merge-conflict/lab-02.html) --> 

6. [dplyr(ii)](lecture/l05b-advanced-dplyr.html)
    *  [Lab 3](hw_lab_instruction/lab03-laquinta-uno/lab03-laquinta-uno.html). [invitation here](https://classroom.github.com/a/CH-fJmTT). (Deadline: 30-September 2023 5PM EDT)
  
    <!-- * Lab 3 [solutions](hw_lab_instruction/lab03-laquinta-uno/lab-03.html) -->

7. [Factors and dates](lecture/l07-factors-dates.html)
    *  Continue working on Lab 3 
    *  HW 2 assigned.  [instructions](hw_lab_instruction/hw02-accidents/hw02-accidents.html) and repo (accept GH classroom [invite](https://classroom.github.com/a/w5VoBhPu)). (Deadline: 09-October 2023 5PM EDT)

<!--     * HW 2 [solutions](hw_lab_instruction/hw02-accidents/hw02.html) --> 

8.  Effective data visualization [(i)](lecture/03a2-tips-for-effective-dataviz.pdf) [(ii)](lecture/03b-tips-for-effective-dataviz.pdf) [video](https://youtu.be/ZrifrBvFWgg)
[Gapminder](https://www.ted.com/talks/hans_rosling_the_best_stats_you_ve_ever_seen)
[More Hans Rosling](https://www.ted.com/talks/hans_rosling_new_insights_on_poverty)

9. [Data from files](lecture/l09-data-from-files.html)
    *   Repository for lecture 9 [here](https://classroom.github.com/a/AwXYGTRA) will not be graded, but gets you everything you need at once.
    *  [Lab 4](hw_lab_instruction/lab04-laquinta-dos/lab04-laquinta-dos.html).  New groups! At least one new teammate for each person. [Invitation here](https://classroom.github.com/a/2z0gKEx2). Deadline: 16-October 2023 5PM EDT

    
<!--     * Lab 4 [solutions](hw_lab_instruction/lab04-laquinta-dos/lab04.html) --> 

10. [Text processing](lecture/l10-text.html)
    * HW 3 assigned.  [instructions](hw_lab_instruction/hw03-fatal-geography/hw03-fatal-geography.html) and repo (accept GH classroom [invite](https://classroom.github.com/a/2qAFEsSR)).

    <!-- * HW 3 [solutions](hw_lab_instruction/hw03-fatal-geography/hw03.html) -->

12. [Text analysis](lecture/l10-text-ii.html)
    *  Reading: [r4ds chapter 14](https://r4ds.had.co.nz/strings.html)
    *  [Lab 5](hw_lab_instruction/lab05-sadplots/lab05-sadplots.html). [Invitation here](https://classroom.github.com/a/Ylc0yTwY).


13. [Matrices, indexing, linear algebra](lecture/l11-linear-algebra-indexing.html)

<!--      * Lab 5 [solutions](hw_lab_instruction/lab05-sadplots/lab05.html) --> 

<!-- 15. [Functions i](lecture/l12-functions-i.html).  -->
<!-- 16. [Functions ii and iteration](lecture/l13-functions-ii.html). -->
<!--        [Lab 6](hw_lab_instruction/lab06-covid-times/lab06-covid-times.html) assigned, any groups as you like. [Invitation here](https://classroom.github.com/a/6GAvWurq). Due 5pm, Nov 16. --> 
<!--      * Lab 6 [solutions](hw_lab_instruction/lab06-covid-times/lab06.html) --> 
<!-- 17.  [Knitr tricks and debugging](lecture/l14-debugging.html).  -->
<!--  *  HW 4 assigned (revised to shorten it!!).  [instructions](hw_lab_instruction/hw05-modeling-gss/hw-04-modeling-gss.html) and repo (accept GH classroom [invite](https://classroom.github.com/a/rNXgxZex)).   --> 
<!--      * HW 4 [solutions](hw_lab_instruction/hw05-modeling-gss/hw-04.html) --> 
<!--  * Work on Lab 6 --> 
<!-- 18.  [Linear models](lecture/l15-linear-models.html) -->
<!--  * Work on Lab 6 --> 
<!-- 19. Final Exam.  -->
<!--  * Remember I will be looking at the `.md` for results and the `.Rmd` for your code. [instructions](hw_lab_instruction/final-modeling.html) and repo (accept GH classroom [invite](https://classroom.github.com/a/eebbYmkV)).  Due 5pm EDT, Nov 10. --> 
<!-- 20.   [Multivariate linear models and Prediction](lecture/l16-crossv-lm.html)  -->

<!-- 20.  [Multivariate linear models](lecture/l16-multivariate-lm.html) -->
<!-- 21.  [Prediction and logistic regression](lecture/l17-prediction-logistic.html) -->
